In [9]:
#creating RANK 1 numpy array (one dimensional)
import numpy as np
an_array = np.array([3,33,333]) #create a rank 1 array
print(an_array)

[  3  33 333]


In [10]:
print(type(an_array)) #to print the type

<class 'numpy.ndarray'>


In [11]:
#to find shape or dimension 
print(an_array.shape)

(3,)


In [12]:
# to print a specific value 
print(an_array[0])

3


In [13]:
#to print multiple values
#and because this is rank 1 array, we need only one index to access the element
print(an_array[1],an_array[2])

33 333


In [14]:
#ndarrays are mutable so we can change the elements 
an_array[0] = 888
print(an_array)

[888  33 333]


**Creating 2 dimensional or Rank 2 numoy array**

In [15]:
another = np.array([[11,12,13],[21,22,23]]) #creating rank 2 array
print(another)

[[11 12 13]
 [21 22 23]]


In [16]:
#to find shape of array
print("The shape is 2 rows and 3 cloumns", another.shape) #rows x columns

The shape is 2 rows and 3 cloumns (2, 3)


In [18]:
#to access an element in an array
print("Accessing elemts [0,0],[0,1] and [1,0] of the ndarray:", another[0,0], another[0,1], another[1,0])

Accessing elemts [0,0],[0,1] and [1,0] of the ndarray: 11 12 21


In [19]:
#create a 2x2 array of zeros (using zeros function)
example1 = np.zeros((2,2))
print(example1)

[[0. 0.]
 [0. 0.]]


In [21]:
#create a 2x2 array filled with same number 4.0
example2 = np.full((2,2),4.0)
print(example2)

[[4. 4.]
 [4. 4.]]


In [22]:
#create a 3x3 array matrix with a diganol 1s and others 0
example3 = np.eye(3,3)
print(example3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
#create an array of ones
example4 = np.ones((2,3))
print(example4)

[[1. 1. 1.]
 [1. 1. 1.]]


In [24]:
print(example4.shape)

(2, 3)


In [25]:
#now to access elements in this, we need to
print(example4[0,1])

1.0


In [26]:
#create an array of random floats between 0 and 1
example5 = np.random.random((2,2))
print(example5)

[[0.6299422  0.27070153]
 [0.6471657  0.6307468 ]]
