## Slice Indexing

In [1]:
import numpy as np

#Rank 2 array of shape (3,4)
an_array = np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [2]:
#use array slicing to get a subarray consisting of the first 2 rows x 2 columns
example_of_slicing = an_array[:2,1:3]
print(example_of_slicing)

[[12 13]
 [22 23]]


In [3]:
example_of_slicing[0,0]

12

In [4]:
#changing an element
#inspect the element at 0,1
print("Before:", an_array[0,1]) 
#example_of_slicing [0,0] is the same data as an_array[0,1] 
example_of_slicing[0,0] = 1212
print("After:", an_array[0,1])

Before: 12
After: 1212


In [5]:
print(an_array)

[[  11 1212   13   14]
 [  21   22   23   24]
 [  31   32   33   34]]


Now you can see that changing value in **example_of_slicing** changes the values in **an_array** because example_of_slicing is reference of an_array

**Now if you want to make a copy you should use np.array and make a new copy**

In [6]:
example_of_slicing = np.array(an_array[:2,1:3])
print(example_of_slicing)

[[1212   13]
 [  22   23]]


Now if I replace the element in example_of_slicing, it will not change data in an_array

In [8]:
#changing an element
#inspect the element at 0,1
print("Before:", an_array[0,1]) 
#example_of_slicing [0,0] is the same data as an_array[0,1] 
example_of_slicing[0,0] = 1213
print("After:", an_array[0,1])

Before: 1212
After: 1212


In [9]:
#creating a rank 2 array of shape (3,4) 
an_array1 = np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])
print(an_array1)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [11]:
#using both integer indexing & slicing generates an array of lower rank
row_rank1 = an_array1[1,:] #rank 1 view
print(row_rank1)

[21 22 23 24]


In [17]:
print(an_array1[:2,])

[[11 12 13 14]
 [21 22 23 24]]


In [18]:
print(row_rank1.shape)

(4,)


In [19]:
#using slicing alone generates an array of the same rank as the an_array
row_rank2 = an_array1[1:2,:] #rank 2 view
print(row_rank2, row_rank2.shape) #notice the [[]] 

[[21 22 23 24]] (1, 4)


In [20]:
#We can do the same thing for columns of an array:
print()
col_rank1 = an_array1[:,1]
col_rank2 = an_array1[:,1:2]

print(col_rank1, col_rank1.shape) #Rank 1
print()
print(col_rank2, col_rank2.shape) #Rank 2


[12 22 32] (3,)

[[12]
 [22]
 [32]] (3, 1)


### Array Indexing for changing elements:

In [22]:
#creating a new array
an_array2 = np.array([[11,12,13],[21,22,23],[31,32,33],[41,42,43]])
print("Original Array:")
print(an_array2)

Original Array:
[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]


In [24]:
#create an array of indicies
col_indices = np.array([0,1,2,0])
print("Col indices picked:", col_indices)

row_indices = np.arange(4)
#np.arange function is used to arrange values as given in output
print("Row indices picked:", row_indices)

Col indices picked: [0 1 2 0]
Row indices picked: [0 1 2 3]


In [25]:
#Examine the pairing of row_indices and col_indices
for row,col in zip(row_indices,col_indices):
    print(row,":",col)

0 : 0
1 : 1
2 : 2
3 : 0


In [34]:
#example of how zip works
a = ("John", "Charles", "Mike")
b = ("Jenny", "Christy", "Monica")

x = zip(a,b)
#using the tuple() function to display a readable version of the result
print(tuple(x))


(('John', 'Jenny'), ('Charles', 'Christy'), ('Mike', 'Monica'))


In [35]:
#select one element from each row
print("value in the array at those indices:", an_array2[row_indices,col_indices])

value in the array at those indices: [11 22 33 41]


In [36]:
#change one element from each row using the indices selected
an_array2[row_indices, col_indices] += 100000

print("Changed Array")
print(an_array2)

Changed Array
[[100011     12     13]
 [    21 100022     23]
 [    31     32 100033]
 [100041     42     43]]


Keep this trick in mind because it will help in data cleaning