**Suppose we want to clean all ages in a data set less than 0 and greater than 100**

In [3]:
#creating a 3 x 2 array
#always remember to import numpy
import numpy as np
an_array = np.array([[11,12],[21,22],[31,32]])
print(an_array)

[[11 12]
 [21 22]
 [31 32]]


In [6]:
#create a filter which will be boolean for whether each element meets the requirement or not
filter = (an_array > 15)
filter

array([[False, False],
       [ True,  True],
       [ True,  True]])

Notice that the filter is a same ndarray as an_array which is filled with **True** for each element whose corresponding element is an_array which is greater than 15 and **False** for those elements whose value is less than 15

In [7]:
#we can also select those element which meet the criteria
print(an_array[filter])

[21 22 31 32]


In [8]:
#simple step for above operation
#we could have just used the approach below without the need for the filter

an_array[an_array>15]

array([21, 22, 31, 32])

In [9]:
#some more complex feature like values greater than 20 and less than 30
an_array[(an_array>20) & (an_array<30)]

array([21, 22])

In [10]:
#or if we want just even number
an_array[an_array % 2 == 0]

array([12, 22, 32])

Now if we want to change the element based on a condition
**what is particularly useful is that we can actually change elements in the array applying a similar logical filter. Let's add 100 to all the even values**

In [11]:
an_array[an_array % 2 == 0] +=100
print(an_array)

[[ 11 112]
 [ 21 122]
 [ 31 132]]
