In [2]:
import numpy as np
example1 = np.array([11,12])
#python assigns the data type
print(example1.dtype)

int64


In [3]:
example2 = np.array([11.0,12.0])
#python assigns the data type
print(example2.dtype)

float64


In [4]:
example3 = np.array([11,21], dtype=np.int64)
#you can also tell python the data type
print(example3.dtype)

int64


In [6]:
#you can use this to force floats into integers (using floor function) 
example4 = np.array([11.1,12.7], dtype = np.int64)
print(example4.dtype)
print()
print(example4)

int64

[11 12]


In [7]:
#you can also use this to force integers into floats if you anticipate
#the values may change to floats later
example5 = np.array([11,21], dtype = np.float64)
print(example5.dtype)
print()
print(example5)

float64

[11. 21.]


## Arithmetic Array Operations:

In [8]:
x = np.array([[111,112],[121,122]], dtype=np.int)
y = np.array([[211.1,212.1],[221.1,222.1]], dtype=np.float64)

print(x)
print()
print(y)

[[111 112]
 [121 122]]

[[211.1 212.1]
 [221.1 222.1]]


In [9]:
#Addition
print(x+y)

[[322.1 324.1]
 [342.1 344.1]]


In [10]:
#Addition other way
print(np.add(x,y)) #numpy add function

[[322.1 324.1]
 [342.1 344.1]]


In [11]:
#subract
print(x-y)

[[-100.1 -100.1]
 [-100.1 -100.1]]


In [12]:
#subtract other way
print(np.subtract(x,y)) # numpy subtract function

[[-100.1 -100.1]
 [-100.1 -100.1]]


In [13]:
#multiply
print(x*y)
print()
print(np.multiply(x,y)) #multiply function of numpy

[[23432.1 23755.2]
 [26753.1 27096.2]]

[[23432.1 23755.2]
 [26753.1 27096.2]]


In [14]:
#divide
print(x/y)
print()
print(np.divide(x,y)) #divide function of numpy

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]


In [17]:
#square root
print(np.sqrt(x)) #sqrt function of numpy

[[10.53565375 10.58300524]
 [11.         11.04536102]]


In [18]:
#exponent (e ** x)
print(np.exp(x)) #exp function of numpy

[[1.60948707e+48 4.37503945e+48]
 [3.54513118e+52 9.63666567e+52]]
