## Statistical Sorting and Set Operations

In [3]:
#setup a random 2 x 4 matrix
import numpy as np
rrr = np.random.randn(2,5)
print(rrr)

[[-0.54867861 -0.46289461  0.07871258 -0.46888786  0.97381144]
 [ 1.01805119 -1.48678326  0.26963105  1.56116179  0.59996373]]


Above np.random.randn returns a sample from the "standard normal" distribution.

In [4]:
#setup a random 2 x 4 matrix
arr = 10 * np.random.randn(2,5) # we can multiply, subtract, add or divide as per our need
print(arr)

[[  3.35349445  10.07213522  14.36165763  -6.24902096  14.04409699]
 [ 11.29285897   3.70542107  11.05083694   0.37466029 -13.01040753]]


In [5]:
#compute the mean for all elements
print(arr.mean()) #mean function of numpy

4.899573308203356


In [6]:
#compute the mean by row
print(arr.mean(axis = 1))

[7.11647267 2.68267395]


In [7]:
#compute the mean by column
print(arr.mean(axis = 0))

[ 7.32317671  6.88877815 12.70624729 -2.93718034  0.51684473]


In [8]:
#sum all elements
print(arr.sum())

48.99573308203357


In [12]:
#compute the medians or rows
print(np.median(arr, axis = 1))

[10.07213522  3.70542107]


In [13]:
#compute the medians of columns
print(np.median(arr, axis = 0))

[ 7.32317671  6.88877815 12.70624729 -2.93718034  0.51684473]


## Sorting

In [15]:
#create a 10 element array of randoms
unsorted = np.random.randn(10)
print(unsorted)

[-0.96799458 -1.01104194  0.03289942 -0.369841    0.18923569  0.06801163
 -1.70588975  0.89110527  2.03925298  1.38253332]


In [16]:
#create copy and sort
sorted = np.array(unsorted)  #creates a copy
sorted.sort()                # sort elements using sort function from numpy

print(sorted)
print()
print(unsorted)

[-1.70588975 -1.01104194 -0.96799458 -0.369841    0.03289942  0.06801163
  0.18923569  0.89110527  1.38253332  2.03925298]

[-0.96799458 -1.01104194  0.03289942 -0.369841    0.18923569  0.06801163
 -1.70588975  0.89110527  2.03925298  1.38253332]


### Finding Unique Elements

In [17]:
array = np.array ([1,2,1,3,4,4,2,5,7])

print(np.unique(array))

[1 2 3 4 5 7]


### Set Operations with np.array data type

In [18]:
s1 = np.array(["desk","Chair","bulb"])
s2 = np.array(["lamp","bulb","chair"])
print(s1,s2)

['desk' 'Chair' 'bulb'] ['lamp' 'bulb' 'chair']


In [20]:
#intersection
print(np.intersect1d(s1, s2))  # we use intersect1d becoz intersect expects 1d arrays

['bulb']


In [21]:
#union
print(np.union1d(s1,s2))  # we use union1d becoz union expects 1d arrays

['Chair' 'bulb' 'chair' 'desk' 'lamp']


In [24]:
#elements in s1 that are not in s2
print(np.setdiff1d(s1,s2))
#the answe is showing Chair because "Chair" and "chair" are different for python string

['Chair' 'desk']


In [25]:
#which element of s1 is also in s2
print(np.in1d(s1,s2))

[False False  True]
