## Broadcasting

![title](img/image1.png)
**When operating on two arrays, NumPy compares their shapes element-wise. It starts with trailing dimensions, and works its way forward. Two dimensiona re compatible when:**
   * They are equal, or
   * one of them is 1"
   
 This diagram below is just for illustration purpose. B actually retains the original shape and that's the beauty of bradcasting.
![title](img/image2.png)

In [1]:
import numpy as np

start = np.zeros ((4,3))  #this creates a 4x3 matrix with zeros in it
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [2]:
#create a rank 1 ndarray with 3 values
add_rows= np.array([1,0,2])
print(add_rows)

[1 0 2]


In [3]:
y = start + add_rows #add to each row of 'start' using broadcasting
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [12]:
#create a ndarray which is 4x1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])   #created a 1x4 array
add_cols = add_cols.T       #used Transverse function "T" to convert to 4x1 array

print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [13]:
# add to each column of 'start' using broadcasting
y = start + add_cols
print(y)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [14]:
# this will braodcast in both dimensions
add_scalar = np.array([2])
print(add_scalar + start)

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [15]:
a = np.array([[0,0],[0,0]])
b1 = np.array ([1,1])
b2 = 1

print(a+b1)

print()

print(a+b2)

[[1 1]
 [1 1]]

[[1 1]
 [1 1]]
